export const projects = [
  {
    id: '01',
    period: '2024.09',
    competition: '2024 “华为杯”中国研究生数学建模竞赛',
    title: '数据驱动下磁性元件的磁芯损耗建模',
    role: '队长（1/3）',
    summary: '针对磁性元件损耗预测与工况优化问题，从实验数据处理、损耗预测到工况优化完成完整建模分析。',
    details: [
      '完成数据清洗、特征提取与预处理，结合 PCA 降维、相关性分析和交互特征构造，构建分类模型，精确率达 98.96%。',
      '通过函数拟合修正标准方程，进一步构建磁芯损耗最小化与传输磁能最大化的多目标优化模型。',
    ],
    highlight: '5万余字',
    highlightLabel: '项目报告 · 获全国二等奖',
    tags: ['数据清洗', 'PCA', '函数拟合', '多目标优化'],
    tone: 'blue',
    download: './projects/2024-mathematical-modeling-paper.pdf',
    downloadName: '赵丽蓉-2024研究生数学建模国赛论文.pdf',
  },
  {
    id: '02',
    period: '2022.10 — 2023.02',
    competition: '2022 浙江省物流设计大赛',
    title: '双碳背景下循环包装箱 C 端运营解决方案',
    role: '负责人（1/5）',
    summary: '围绕循环包装回收难点，以系统仿真优化配送方案，用 DBSCAN 规划回收网络，并设计消费者激励机制。',
    details: [
      '基于网络调研与 SWOT 分析拆解循环包装箱在回收、配送和用户参与上的运营难点。',
      '通过系统仿真优化驿站与社区配送，使用 DBSCAN 规划回收网络，并以演化博弈设计消费者激励制度。',
    ],
    highlight: '6.2万余字',
    highlightLabel: '项目报告 · 获省赛二等奖',
    tags: ['DBSCAN', '系统仿真', 'SWOT', '行为决策'],
    tone: 'pink',
    download: './projects/circular-packaging-solution.pdf',
    downloadName: '脉脉箱通-双碳背景下循环包装箱C端运营解决方案.pdf',
  },
  {
    id: '03',
    period: '2026.02 — 至今',
    title: 'AI Agent 驱动的自媒体运营与 SOP 自动化',
    role: 'AI 个人实践',
    summary: '将选题、AI 作图、文案生成、排版与发布串联为一体化流程，沉淀可复用的自动化内容运营 SOP。',
    details: [
      '基于 OpenClaw 部署自动化发布工作流，接入 Gemini 图像生成与 Claude 文案生成。',
      '结合 Python + CDP 浏览器自动化，完成从选题输入到排版发布的一体化内容运营 SOP。',
    ],
    highlight: '1 FLOW',
    highlightLabel: '端到端运营流程',
    tags: ['OpenClaw', 'Gemini', 'Claude', 'Python + CDP'],
    tone: 'lilac',
  },
  {
    id: '04',
    period: '2026.07',
    title: 'OfferPath｜运营面试知识管理平台',
    role: 'AI 个人实践',
    summary: '把分散面经转化为结构化题库，串联截图收集、内容提取、答案优化、能力分类与复习进度管理。',
    details: [
      '打通微信截图收集、AI 内容提取、答案优化、能力标签分类与学习进度管理流程。',
      '将小红书、牛客网、知乎等碎片化面经沉淀为可按岗位、难度和掌握状态复习的结构化题库。',
    ],
    highlight: '5 STEP',
    highlightLabel: '面试资料处理闭环',
    tags: ['内容提取', '答案优化', '能力标签', '学习进度'],
    tone: 'blue',
    url: 'https://offerpath.rinazhao.top/',
  },
  {
    id: '05',
    period: '2026.07',
    title: '岸题录 ShoreNote｜专业知识错题库',
    role: 'AI 个人实践',
    summary: '面向专业知识复盘场景，完成需求拆解、产品设计与持续迭代，支持资料导入、智能解析和错题归档。',
    details: [
      '针对错题分散、整理效率低和复盘困难，独立完成需求拆解、产品设计、功能开发与持续迭代。',
      '支持多格式资料导入、智能解析、分类归档、错题复盘与学习笔记管理，形成“收集—整理—复习”闭环。',
    ],
    highlight: '3 STEP',
    highlightLabel: '收集—整理—复习',
    tags: ['产品设计', '智能解析', '分类归档', '错题复盘'],
    tone: 'pink',
    url: 'https://shorenote.rinazhao.top/',
  },
]

export const experience = [
  {
    date: '2023.10 — 2024.01',
    company: '杭州直行便供应链有限公司',
    role: '采购管理实习生',
    description: '跟踪 D2C 海外订单履约全流程，用指标监控与异常分类推动采购、仓库、商家和业务团队协同。',
    metrics: ['仓库 7 天发货率 ≈ 70%', '店铺 3 天发货率 > 85%', '履约交付率 ≥ 90%'],
  },
  {
    date: '2021.03 — 2023.10',
    company: '浙江工商大学管理工程与电子商务学院',
    role: '学办助理',
    description: '在高任务量下处理 200+ 毕业档案及跨部门事务，持续保证信息准确与推进节奏。',
    metrics: ['200+ 份档案', '多部门协作', '长期在岗 2.5 年'],
  },
]

export const skillCards = [
  {
    id: 'python',
    name: 'Python 数据分析',
    category: 'skill',
    image: './skills-hobbies/python-data-analysis.webp',
    description: '熟练使用 Python 进行数据清洗、特征处理、统计分析与自动化脚本开发，能将重复的数据任务整理为可复用流程。',
    tone: 'lilac',
  },
  {
    id: 'excel',
    name: 'Excel 数据分析',
    category: 'skill',
    image: './skills-hobbies/excel-data-analysis.webp',
    description: '能够使用函数、数据透视表、图表与数据整理工具完成运营分析、指标跟踪和结构化报表输出。',
    tone: 'blue',
  },
  {
    id: 'sql',
    name: 'SQL',
    category: 'skill',
    image: './skills-hobbies/sql.webp',
    description: '掌握查询、筛选、聚合与多表关联等操作，能够围绕业务问题提取并整理分析所需数据。',
    tone: 'pink',
  },
  {
    id: 'english',
    name: 'CET-4 / CET-6',
    category: 'skill',
    image: './skills-hobbies/english-cet.webp',
    description: '已通过大学英语四、六级考试，具备良好的英语读写译能力，能够阅读专业资料并完成日常书面沟通。',
    tone: 'blue',
  },
  {
    id: 'vibecoding',
    name: 'Vibecoding',
    category: 'skill',
    image: './skills-hobbies/vibecoding.webp',
    description: '善用 AI 辅助需求拆解、代码生成、调试与产品迭代，已独立完成多个可上线使用的个人项目。',
    tone: 'lilac',
  },
  {
    id: 'account-operations',
    name: '账号运营',
    category: 'skill',
    image: './skills-hobbies/account-operations.webp',
    description: '具备内容选题、采写、排版、发布和数据复盘经验，能够将账号运营流程拆解为可执行动作。',
    tone: 'pink',
  },
  {
    id: 'power-bi',
    name: 'Power BI',
    category: 'skill',
    image: './skills-hobbies/power-bi.webp',
    description: '能够围绕业务指标搭建可视化看板，通过图表联动呈现趋势、结构与异常，为运营判断提供支持。',
    tone: 'blue',
  },
  {
    id: 'photoshop',
    name: 'Photoshop',
    category: 'skill',
    image: './skills-hobbies/photoshop.webp',
    description: '掌握抠图、调色、图像优化与基础版式制作，可配合内容运营完成日常视觉素材处理。',
    tone: 'pink',
  },
  {
    id: 'feishu-bitable',
    name: '飞书多维表搭建',
    category: 'skill',
    image: './skills-hobbies/feishu-bitable.webp',
    description: '能够基于业务流程设计字段、视图、表间关联与自动化规则，用于数据管理、任务协同和可视化追踪。',
    tone: 'lilac',
  },
  {
    id: 'singing',
    name: '唱歌',
    category: 'hobby',
    image: './skills-hobbies/singing.webp',
    description: '喜欢用歌声调节状态，也享受从反复练习到完整表达的过程，让专注与情绪找到平衡。',
    tone: 'pink',
  },
  {
    id: 'travel',
    name: '旅行',
    category: 'hobby',
    image: './skills-hobbies/travel.webp',
    description: '喜欢在不同城市观察生活、空间与商业细节，在陌生环境中保持好奇并积累新的视角。',
    tone: 'blue',
  },
  {
    id: 'walking',
    name: '散步',
    category: 'hobby',
    image: './skills-hobbies/walking.webp',
    description: '习惯通过散步整理思路、恢复节奏，在稳定的日常活动中获得持续思考和重新出发的空间。',
    tone: 'lilac',
  },
  {
    id: 'fuse-beads',
    name: '拼豆',
    category: 'hobby',
    image: './skills-hobbies/fuse-beads.webp',
    description: '享受把像素图案逐颗变成实体作品的过程，在颜色组合与细节制作中练习耐心和专注。',
    tone: 'pink',
  },
  {
    id: 'photography',
    name: '拍照',
    category: 'hobby',
    image: './skills-hobbies/photography.png',
    description: '喜欢记录人物、场景和容易被忽略的细节，通过构图与光线保存真实而有温度的瞬间。',
    tone: 'blue',
  },
]
